#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ryuki Kodato 
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0
for line in sys.stdin:
    try:
        sna += int(line)
    except:    
        ans += float(line)

print(ans)
